### PR TITLE
fix PermitRootLogin param to be more idempotent

### PR DESCRIPTION
**Pull request by ericoc**
this should make PermitRootLogin parameter be idempotent

### CODE REVIEW

**Comment by MooseQuest** [comment]
😎

**Review by lottspot — APPROVED** [review]
Very awesome! Thanks for this :)

**Comment by ericoc** [comment]
I just realized who you are looking over my old PRs now @lottspot ! @MooseQuest introduced us - thanks again for that cider at City Hall.

**Comment by lottspot** [comment]
cheers 🙂

**Pull request merged**
